<script>
  // Modular, swappable icon for Svelte components.
  // Maps logical names to heroicon utility classes generated by the Tailwind plugin.
  export let name = ''
  export let variant = null // 'solid' | 'mini' | 'micro' | null
  export let className = ''

  const map = {
    // Common UI
    home: 'home',
    topics: 'chat-bubble-left-right',
    chat: 'chat-bubble-left-right',
    bookmark: 'bookmark',
    bookmark_solid: 'bookmark-solid',
    bell: 'bell',
    users: 'user-group',
    trophy: 'trophy',
    info: 'information-circle',
    warning: 'exclamation-triangle',
    close: 'x-mark',
    ellipsis: 'ellipsis-horizontal',
    sun: 'sun',
    moon: 'moon',
    search: 'magnifying-glass',
    play: 'play',
    bolt: 'bolt',
    briefcase: 'briefcase',
    adjustments_vertical: 'adjustments-vertical',
    chevron_up: 'chevron-up',
    chevron_down: 'chevron-down',
    building: 'building-office-2',
    // forum icons
    bars_3: 'bars-3',
    envelope: 'envelope',
    envelope_solid: 'envelope-solid',
    lock_closed: 'lock-closed',
    check_circle: 'check-circle',
    arrow_up: 'arrow-up',
    pin: 'map-pin',
    reply: 'arrow-uturn-left'
  }

  function resolve(n, v) {
    if (!n) return ''
    if (n.startsWith('hero-')) return n
    const base = map[n] ?? n
    let suffix = ''
    if (base.endsWith('-solid') || base.endsWith('-mini') || base.endsWith('-micro')) {
      suffix = ''
    } else if (v && ['solid', 'mini', 'micro'].includes(v)) {
      suffix = `-${v}`
    }
    return `hero-${base}${suffix}`
  }

  $: resolved = resolve(name, variant)
</script>

<span class={`${resolved} ${className}`}></span>
