defmodule UrielmWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :urielm

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_urielm_key",
    signing_salt: "K4fuzxis",
    same_site: "Lax"
  ]

  # The `secure` flag on the session cookie is driven from config
  # (`config :urielm, :secure_session_cookie`) so it is enabled in production
  # (HTTPS) but stays off in dev/test where local development runs over http.
  # Resolved at request time so `config/runtime.exs` takes effect for releases.
  def session_options do
    Keyword.put(
      @session_options,
      :secure,
      Application.get_env(:urielm, :secure_session_cookie, false)
    )
  end

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: {__MODULE__, :session_options, []}]],
    longpoll: [connect_info: [session: {__MODULE__, :session_options, []}]]

  socket "/socket", UrielmWeb.UserSocket,
    websocket: [connect_info: [session: {__MODULE__, :session_options, []}]],
    longpoll: [connect_info: [session: {__MODULE__, :session_options, []}]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :urielm,
    gzip: not code_reloading?,
    only: UrielmWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug :session

  defp session(conn, _opts) do
    Plug.Session.call(conn, Plug.Session.init(session_options()))
  end

  plug UrielmWeb.Router
end
